config/routes.rb
DynamicAccessibility::Application.routes.draw do

  root 'main#index'

  resources :participants do 
    put :toggle_consent, :on => :member
  end
  resources :participant_sessions
  resources :tasks

  post 'submit' => 'tasks#update'

  get 'register' => 'participants#new'

  get 'about' => 'main#about'
  get 'resources' => 'main#resources'
  get 'login' => 'participant_sessions#new'
  get 'logout' => 'participant_sessions#destroy'

  

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  validates :email, :uniqueness => { :case_sensitive => false }
  validates :device, :inclusion => { :in => ['smartphone', 'tablet', 'desktop', 'other'] }
  validates :age, :numericality => { :only_integers => true }
  validates :tech_ability, :numericality => { :only_integers => true }
  validates :tech_ability, :inclusion => { :in => 1..5 }
  # add email validation

  has_many :completed_tasks
  has_many :scores
  has_many :tasks, :through => :completed_tasks

  acts_as_authentic do |c|
    c.logged_in_timeout = 24.hours
  end

  scope :selected, -> { where(is_selected: true) }

  def self.avg_by_activity(metric, task_id, activity_id)
    avg = 0
    total = 0
    length = 0

    Participant.selected.each do | p |
      v = p.completed_tasks.where(:task_id => task_id, :activity_id => activity_id).first()[metric]
      if (v > 0)
        total += v
        length += 1
      end
    end
    if length > 0
      avg = total / length
    end

    avg
  end

  def self.quartile_by_activity(metric, task_id, activity_id)
    values = []

    Participant.selected.each do | p |
      v = p.completed_tasks.where(:task_id => task_id, :activity_id => activity_id).first()[metric]
      if (!v.nil?)
        values.push(v)
      end
    end

    values.sort

    #pass in the user's id
    #find position
  end

  def quartile(metric, type)
    value = self.completed_tasks.by_type(type).average(metric)
    larger = []
    smaller = []

    puts type, value

    Participant.selected.each do | p |
      if (p.id != self.id)
        v = p.completed_tasks.by_type(type).average(metric)

        puts v
        if !v.nil?
          if v >= value
            larger.push(v)
          else
            smaller.push(v)
          end
        end
      end
    end

    total = larger.size + smaller.size

    puts smaller.size
    puts larger.size

    puts total

    if total == 0
      return 4
    elsif (total > 0) 

      if type == 'success_rate'
        percentile = larger.size / total
      else
        percentile = smaller.size / total
      end

      puts percentile

      if percentile == 0
        return 4
      elsif percentile <= 0.25
        return 3
      elsif percentile <= 0.5
        return 2
      elsif percentile <= 0.75
        return 1
      else
        return 0
      end
    else 
      return 0
    end
  end

  def correctness_quartile(type)
    value = self.completed_tasks.by_type(type).average('success_rate')
    larger = []
    smaller = []

    Participant.selected.each do | p |
      if (p.id != self.id)
        v = p.completed_tasks.by_type(type).average('success_rate')

        if v > value
          larger.push(v)
        else
          smaller.push(v)
        end
      end
    end

    total = larger.size + smaller.size

    if total == 0
      return 4
    elsif (total > 0) 

      percentile = larger.size / total

      if percentile == 0
        return 4
      elsif percentile <= 0.25
        return 3
      elsif percentile <= 0.5
        return 2
      elsif percentile <= 0.75
        return 1
      else
        return 0
      end
    else 
      return 0
    end
  end

  def set_level(type)
    error_quart = self.quartile('error_rate', type)
    correctness_quart = self.quartile('success_rate', type)
    time_quart = self.quartile('time', type)

    puts error_quart
    puts correctness_quart
    puts time_quart

    avg = (error_quart + correctness_quart + time_quart) / 3
    current_score = self.scores.by_type(type).first()

    if current_score.nil?
      current_score = Score.new({
        :participant_id => self.id,
        :activity_type => type,
        :score => avg < 3 ? 1 : 0
      })

      current_score.save
    elsif avg < 3 && current_score.score < 4
      Score.update(current_score.id, :score => current_score.score + 1)
    end
  end

  def level(type)
    score = self.scores.by_type(type).first()

    return score.nil? ? 0 : score.score
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def index
    if current_participant.nil?
      redirect_to "/login"
    elsif  current_participant.group != 'C'
      redirect_to current_participant
    end

    @participants = {
      :A => Participant.where(:group => 'A'),
      :B => Participant.where(:group => 'B')
    }

    @tasks = Task.all

    @activities = []

    @tasks.each do |task|
      info = YAML.load_file('public/tasks/task_' + task.id.to_s + '.yaml')

      @activities.push(info['activities'])
    end
  end

  def new
    @participant = Participant.new
  end

  def show
    if current_participant.nil?
      redirect_to "/login"
    end

    begin
      @participant = Participant.find(params[:id])

      if @participant != current_participant
        redirect_to current_participant
      elsif @participant.is_selected && !@participant.consent
        redirect_to edit_participant_path(@participant.id)
      end

      @tasks = Task.all
    rescue
      redirect_to '/'
    end

  end

  def create
    participant_params

    begin
      @participant = Participant.new(params[:participant])

      respond_to do |format|
        if @participant.save
          format.html { redirect_to @participant, :notice => 'You have been successfully registered.' }
          format.js   {}
          format.json { render :json => @participant, :status => :created, :location => @participant }
        else
          format.html { render :action => "index" }
          format.json { render :json => @participant.errors, :status => :unprocessable_entity }
        end
      end
    rescue
      redirect_to "/register"
    end
  end

  def toggle_consent
    @participant = Participant.find(params[:id])
    @participant.toggle!(:consent)

    respond_to do |format|
      flash[:success] = "You have confirmed your consent."
      format.html { redirect_to @participant }
      format.js
    end
  end

  def edit
    if current_participant.nil?
      redirect_to "/login"
    elsif !current_participant.is_selected || current_participant.consent
      redirect_to current_participant
    end

    begin
      @participant = Participant.find(params[:id])

      if @participant != current_participant
        redirect_to edit_participant_path(current_participant.id)
      elsif !@participant.is_selected || @participant.consent
        redirect_to @participant
      end
    rescue
      redirect_to edit_participant_path(current_participant.id)
    end

  end

  private
  def participant_params
    params.require(:participant).permit!
  end
end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/views/participants/edit.html.erb
<% content_for :body do %>
    <div class="da-consent">
        <div class="da-consent-header">
            <%= image_tag('villanova_csc_letterhead.jpg', :class => 'da-consent-letterhead') %>
        </div>

        <h1 class="da-h1">Consent</h1>
        
        <h2 class="da-h2">Introduction</h2>
        <p>The purpose of this form is to provide you (as a prospective research study participant) with information that may affect your decision as to whether to participate in this research and to record the consent of those who agree to be involved in the study.</p>

        <h2 class="da-h2">Research</h2>
        <p>Andrew Larkin, Master’s Candidate, Software Engineering, Department of Computing Sciences, Villanova University, Principal Investigator, has invited your participation in a research study.</p>

        <h2 class="da-h2">Study Purpose</h2>
        <p>The purpose of this study is to determine the effectiveness in dynamically altering a website user interface based on the perceived ability of the user.</p>  

        <h2 class="da-h2">Description of the Research Study</h2>
        <p>If you decide to participate, then you will join a study being undertaken as a part of graduate research at Villanova University. You will be asked to perform four (4) tasks on a website over a two week period. You will only be asked to complete one task at a time and you will have 48 hours to complete each task. Each task should take no more than 10 minutes to complete. You may use your own device to access the internet and complete the tasks. However, you are asked to use the same device to complete each of the seven tasks and you will be asked to disclose what type of device you used to complete the tasks. Once the task is complete you will be asked to write a brief evaluation of your ability to complete the task. Tasks can be completed at your convenience, so long as they are completed within 48 hours of being issued. These tasks can be completed anywhere.</p>

        <p>In saying YES, you will asked to participate in the two week study. This login will be used to keep a record of your progress through the study.</p>

        <h2 class="da-h2">Risks</h2>
        <p>While every measure will be taken to ensure confidentiality, there is a remote chance that results transmitted over the internet may be intercepted by a malicious third party.</p>

        <h2 class="da-h2">Benefits</h2>
        <p>You will receive no direct benefit by participating in the study.  The results will, however, provide valuable data that will be used to improve the usability and accessibility of online interfaces for all users.</p>

        <h2 class="da-h2">Confidentiality</h2>
        <p>All information obtained in this study is strictly confidential. The results of this research study may be used in reports, presentations, and publications, but the researchers will not identify you. Information about all participants will be retained in a secure database and will be associated with the login generated for each participant. To facilitate communication with each participant, each login will be associated with the participant’s email address for the duration of the study only. Once the study is complete email addresses will be purged. The anonymous data will be retained to assist in the development of future assistive technologies.</p>

        <h2 class="da-h2">Withdrawl Privilege</h2>
        <p>Participation in this study is completely voluntary. If you are a Villanova student participation in this experiment will have no influence on your academic performance. It is all right for you to say NO. Even if you say YES now, you are free to say NO later and to withdraw from the study at any time without affecting your course grade or standing in the program. If you wish to withdraw from the study you may do so at any time by sending an email to <a href="mailto:alarkin2@villanova.edu">alarkin2@villanova.edu</a> from the email address with which you registered for the study.
</p>

        <h2 class="da-h2">Voluntary Consent</h2>
        <p>Any questions you have concerning the research study or your participation in the study, before or after your consent, will be answered by Andrew Larkin, alarkin2@villanova.edu, 856-217-2863. If you have questions about your rights as a subject/participant in this research, or if you feel you have been placed at risk, you can contact the Institutional Review Board at Villanova University through its chairperson, Dr. Suzanne Smeltzer, suzanne.smeltzer@villanova.edu, 610-519-6828.</p>

        <p>This form explains the nature, demands, benefits and any risk of the project. By signing this form you agree knowingly to assume any risks involved. Remember, your participation is voluntary. You may choose not to participate or to withdraw your consent and discontinue participation at any time without penalty or loss of benefit. In signing this consent form, you are not waiving any legal claims, rights, or remedies. A copy of this consent form will be given (offered) to you.</p>

        <%= button_to "YES, I consent to participate in this study", toggle_consent_participant_path(@participant), :class => "da-button-dark", :method => :put %>
    </div>

<% end %>

app/views/participants/index.html.erb
<% content_for :body do %>
    <% types = ['post', 'shopping', 'form', 'download'] %>
    <% metrics = ['time', 'error_rate', 'success_rate'] %>

    <table class="da-results">
    <% @participants.each do |group, participant| %>
        <tr>
            <th class="da-results-header" rowspan="3">ID</th>
            <th class="da-results-header" rowspan="3">Email</th>
            <th class="da-results-header" rowspan="3">Age</th>
            <th class="da-results-header" rowspan="3">Device</th>
            <th class="da-results-header" colspan="4">Score</th>
            <% @tasks.each do |task| %>
                <th class="da-results-header" colspan="<%= task.count*3 %>"><%= task.name %></th>
            <% end %>
        </tr>
        <tr>
            <% types.each do |type| %>
                <th class="da-results-header <%= type %>" rowspan="2"><%= type %></th>
            <% end %>
            <% @tasks.each_with_index do |task, index| %>
                <% task.count.times do |i| %>
                    <th class="da-results-header <%= @activities[index][i]['type'] %>"  colspan="3"><%= i + 1 %></th>
                <% end %>
            <% end %>
        </tr>
        <tr>
            <% @tasks.each_with_index do |task, index| %>
                <% task.count.times do |i| %>
                    <th class="da-results-header <%= @activities[index][i]['type'] %>" >T</th>
                    <th class="da-results-header <%= @activities[index][i]['type'] %>" >E</th>
                    <th class="da-results-header <%= @activities[index][i]['type'] %>" >C</th>
                <% end %>
            <% end %>
        </tr>
        <% participant.each do |p| %>
            <% if p.is_selected && p.consent %>
                <tr>
                    <td class="da-results-cell"><%= p.id %></td>
                    <td class="da-results-cell"><%= p.email %></td>
                    <td class="da-results-cell"><%= p.age %></td>
                    <td class="da-results-cell"><%= p.device %></td>
                    <% types.each do |type| %>
                        <% score = p.scores.where(:activity_type => type).first %>
                        <td class="da-results-cell"><%= score.nil? ? '' : score.score %></td>
                    <% end %>
                    <% @tasks.each do |task| %>
                        <% task.count.times do |i| %>
                            <% completed_task = p.completed_tasks.where(:activity_id => i, :task_id => task.id).first %>
                            <% metrics.each do |m| %>
                                <td class="da-results-cell da-results-metrics"><%= completed_task.nil? ? '' : completed_task[m] %></td>
                            <% end %>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
        <tr>
            <td class="da-results-cell" colspan="4">Averages</td>
            <% types.each do |type| %>
                <td class="da-results-cell"></td>
            <% end %>
            <% @tasks.each do |task| %>
                <% task.count.times do |i| %>
                    <% completed_task = task.completed_tasks.where('activity_id = ? AND participant_id in (?)', i, participant.ids) %>
                        <% metrics.each do |m| %>
                            <td class="da-results-cell"><%= completed_task.nil? ? '' : completed_task.average(m) %></td>
                        <% end %>
                <% end %>
            <% end %>
        </tr>    
    <% end %>
    </table>

    <h2 class="da-h2">Data by type and metric</h2>

    <% types.each do |type| %>
        <% metrics.each do |m|%>
        <h3 class="da-h3"><%= type %> - <%= m %></h3>
        <table class="da-results">
        <% @participants.each do |group, participant| %>
            <% filtered_tasks = {} %>
            <% @tasks.each_with_index do |task, index| %>
                <% filtered_tasks[task.name] = [] %>
                <% task.count.times do |i| %>
                    <% activity = @activities[index][i] %>
                    <% if activity['type'] == type %>
                        <% activity['id'] = i %>
                        <% filtered_tasks[task.name].push(activity) %>
                    <% end %>
                <% end %>
            <% end %>

            <tr>
                <th class="da-results-header" rowspan="3">ID</th>
                <th class="da-results-header" rowspan="3">Email</th>
                <th class="da-results-header" rowspan="3">Age</th>
                <th class="da-results-header" rowspan="3">Device</th>
                <th class="da-results-header">Score</th>
                <% @tasks.each do |task| %>
                    <th class="da-results-header" colspan="<%= filtered_tasks[task.name].length %>"><%= task.name %></th>
                <% end %>
            </tr>
            <tr>
                <th class="da-results-header <%= type %>" rowspan="2"><%= type %></th>
                <% @tasks.each do |task| %>
                    <% filtered_tasks[task.name].each do |activity| %>
                        <th class="da-results-header <%= type %>"  rowspan="2"><%= activity['id'] + 1 %></th>
                    <% end %>
                <% end %>
            </tr>
            <tr>
            </tr>
            <% participant.each do |p| %>
                <% if p.is_selected && p.consent %>
                    <tr>
                        <td class="da-results-cell"><%= p.id %></td>
                        <td class="da-results-cell"><%= p.email %></td>
                        <td class="da-results-cell"><%= p.age %></td>
                        <td class="da-results-cell"><%= p.device %></td>
                        <% score = p.scores.where(:activity_type => type).first %>
                        <td class="da-results-cell"><%= score.nil? ? '' : score.score %></td>
                        <% @tasks.each do |task| %>
                            <% filtered_tasks[task.name].each do |activity| %>
                                <% completed_task = p.completed_tasks.where(:activity_id => activity['id'], :task_id => task.id).first %>
                                <td class="da-results-cell da-results-metrics"><%= completed_task.nil? ? '' : completed_task[m] %></td>
                            <% end %>
                        <% end %>
                    </tr>
                <% end %>
            <% end %>
            <tr class="da-results-lastrow">
                <td class="da-results-cell" colspan="4">Average <%= m %></td>
                <td class="da-results-cell"></td>
                <% @tasks.each do |task| %>
                    <% filtered_tasks[task.name].each do |activity| %>

                        <% completed_task = task.completed_tasks.where('activity_id = ? AND participant_id in (?)', activity['id'], participant.ids) %>
                        <td class="da-results-cell"><%= completed_task.nil? ? '' : completed_task.average(m) %></td>
                    <% end %>
                <% end %>
            </tr>    
        <% end %>
        </table>
        <% end %>
    <% end %>
<% end %>

app/views/participants/new.html.erb
<% content_for :body do %>
    <h2 class="da-h2">Register To Become a Participant</h2>

    <p>By completing this form, you are submitting yourself to be considered as a participant for a two-week trial that will seek to investigate the effectiveness of a new technique for improving user interfaces on the Internet.  Please understand that, by completing this form, you are not obligating yourself in any way to participate in this trial.  Also understand that completing this form does not guarantee participation in the trial, as participants will be selected so as to maintain an even distribution of age, technical expertise and ability.</p> 

    <h3 class="da-h3">What is the commitment?</h3>
    <P>If selected, you will be asked to commit to a two-week trial that will involve completing a series of tasks on a website.  These tasks will be sent via e-mail and will need to be completed within a 24 hour period.  Participants will not be asked to complete more than one task at a time, and completion of the task should require no longer than 20 minutes.</p>

    <h3 class="da-h3">Will there be any compensation?</h3>
    <p>While there is no direct compensation for participating in this trial, the data gained by your participation will be used to improve the usability of the web for all users.</p> 


    <h3 class="da-h3">Fill out the form to register:</h3>
    <% if @participant.errors.any? %>
      <div class="da-form-errors">
        <h4><%= pluralize(@participant.errors.count, "error") %> present:</h4>
     
        <ol class="da-list">
        <% @participant.errors.full_messages.each do |msg| %>
          <li class="da-list-item"><%= msg %></li>
        <% end %>
        </ol>
      </div>
    <% end %>
    <%= form_for(@participant, :remote => true) do |f| %>

        <ol class="da-list">
            <li class="da-list-item">
                <%= f.label :age, :class => 'da-form-label' %>
                <%= f.text_field :age, :class => 'da-input', :'aria-required' => true %>
            </li>

            <li class="da-list-item">
                <%= f.label :email, :class => 'da-form-label' %>
                <%= f.email_field :email, :class => 'da-input', :'aria-required' => true %>
            </li>

            <li class="da-list-item">
                <%= f.label :password, :class => 'da-form-label' %>
                <%= f.password_field :password, :class => 'da-input', :'aria-required' => true %>
            </li>

            <li class="da-list-item">
                <%= f.label :password_confirmation, :class => 'da-form-label' %>
                <%= f.password_field :password_confirmation, :class => 'da-input', :'aria-required' => true %>
            </li>

            <li class="da-list-item">
                <%= f.label :tech_ability, :class => 'da-form-label' %>
                <%= f.select :tech_ability, options_for_select([['Novice', 1], ['Beginner', 2], ['Intermediate', 3], ['Proficient', 4], ['Expert', 5]]) %>
            </li>

            <li class="da-list-item">
                <%= f.label :device, :class => 'da-form-label' %>
                <%= f.select :device, options_for_select([
                    ['Smartphone', 'smartphone'],
                    ['Tablet', 'tablet'],
                    ['Desktop / Laptop', 'desktop'],
                    ['Other Device', 'other']
                ]) %>
            </li>
        </ol>

        <button class="da-button" type="submit" value="submit" alt="Submit your information">Submit</button>
    <% end %>

    <p>If you have any questions or concerns please contact Andrew Larkin at <a href="mailto:alarkin2@villanova.edu" target="_blank">alarkin2@villanova.edu</a></p>

<% end %>

app/views/participants/show.html.erb
<% content_for :body do %>
    <h1 class="da-h1">Trial data for: <%= @participant.email %></h1>

    <% if @participant.is_selected %>

        <table class="da-participant-table">
            <tr>
                <th class="da-participant-header task">Task</th>
                <th class="da-participant-header complete">Percentage Complete</th>
                <th class="da-participant-header start"></th>
            </tr>
            <% @tasks.each do |task| %>

                <% if task.is_active %>
                    <tr>
                        <td><%= task.name %></td>
                        <td><%= (task.completed_tasks.by_participant(@participant.id).length * 100 / task.count) %>%</td>
                        <td>
                            <% if task.completed_tasks.by_participant(@participant.id).length == task.count %>
                                Task Complete
                            <% elsif task.prereq_id.nil? || task.prereq.completed_tasks.by_participant(@participant.id).length == task.prereq.count %>
                                <a href="/tasks/<%= task.id %>" class="da-button">Start Task</a>
                            <% end %>
                        </td>
                    </tr>
                <% end %>

            <% end %>
        </table>

    <% else %>
        <p>Participants will be notified by email once they have been selected for the trial.  Thank you.</p>
    <% end %>
<% end %>